[project]
name = "mindustry-pal"
description = "A CLI for managing Mindustry game versions and campaigns"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Soucelover", email = "mr.ktotov@gmail.com" }
]

keywords = ["mindustry", "cli", "manager", "versions", "campaigns"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Pydantic",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
]

dynamic = ["version"]

# ===================
# Requirements (deps)
# ===================
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.4",
    "termcolor>=3.3.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pyrefly>=0.61.0",
    "ruff>=0.15.10",
]

# =============
# Project Links
# =============
[project.urls]
Repository = "https://github.com/soucelover/mindustry-pal.git"
Issues = "https://github.com/soucelover/mindustry-pal/issues"
Changelog = "https://github.com/soucelover/mindustry-pal/releases"

# ============
# Build System
# ============
[project.scripts]
mindustry-pal = "mindustry_pal.__main__:main"
mindustry = "mindustry_pal.__main__:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

# =============
# Ruff Settings
# =============
[tool.ruff]
line-length = 78 # PEP-8

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules
select = ["ALL"]
ignore = [
    "D",       # Этот репо пока строго не документируется
    "ARG",     # flake8-unused-arguments (иногда полезен для рефакторинга)
    "RUF001",
    "RUF002",
    "RUF003",
    "TD003",   # Вставляем Issue Link, только если создаём Issue
    "FIX",     # Обычно надоедает, но полезно как напоминалка
    "COM812",  # Redundant with formatter
    "PLC0414", # Противоречит семантике неиспользуемых явно импортов
    "EXE001",
]
extend-safe-fixes = ["TC"]
future-annotations = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-builtins]
ignorelist = ["id"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

# ================
# Pyrefly Settings
# ================

[tool.pyrefly]
python-version = "3.14"

[tool.pyrefly.errors]
redundant-cast = "warn"
